import { useEffect, useState } from 'react'
import { Link as RouterLink } from 'react-router-dom'
import {
  Alert as MuiAlert,
  Box,
  Button,
  Chip,
  CircularProgress,
  Link,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  Typography,
} from '@mui/material'
import api from '../api'

type AlertSummary = {
  id: number
  status: string
  created_at: string
  updated_at: string
  score_id: number
}

type AlertsResponse = {
  value: AlertSummary[]
  Count?: number
}

function statusColor(status: string) {
  switch (status) {
    case 'confirmed':
      return 'success'
    case 'watch_list':
      return 'warning'
    case 'dismissed':
      return 'default'
    default:
      return 'info'
  }
}

export default function AlertsListPage() {
  const [alerts, setAlerts] = useState<AlertSummary[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [showOnlyLast7Days, setShowOnlyLast7Days] = useState(true)

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        setLoading(true)
        const res = await api.get<AlertsResponse>('/alerts', { params: { limit: 200 } })
        if (!cancelled) {
          const maybeWrapped = res.data as Partial<AlertsResponse> | AlertSummary[]
          const value = Array.isArray(maybeWrapped)
            ? maybeWrapped
            : (maybeWrapped.value as AlertSummary[] | undefined) ?? []
          setAlerts(value)
        }
      } catch (e) {
        const message = e instanceof Error ? e.message : 'Failed to load alerts'
        if (!cancelled) {
          setError(message)
        }
      } finally {
        if (!cancelled) setLoading(false)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [])

  const now = new Date()
  const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)

  const filteredAlerts = showOnlyLast7Days
    ? alerts.filter((a) => new Date(a.created_at) >= sevenDaysAgo)
    : alerts

  const totalCount = alerts.length
  const last7dCount = alerts.filter((a) => new Date(a.created_at) >= sevenDaysAgo).length
  const confirmedCount = filteredAlerts.filter((a) => a.status === 'confirmed').length
  const watchListCount = filteredAlerts.filter((a) => a.status === 'watch_list').length
  const pendingCount = filteredAlerts.filter((a) => a.status === 'pending_review').length

  if (loading) {
    return (
      <Box display="flex" justifyContent="center" mt={4}>
        <CircularProgress />
      </Box>
    )
  }

  if (error) {
    return (
      <MuiAlert severity="error" sx={{ mt: 2 }}>
        {error}
      </MuiAlert>
    )
  }

  if (!alerts.length) {
    return (
      <Typography variant="body1" sx={{ mt: 2 }}>
        No alerts yet.
      </Typography>
    )
  }

  return (
    <Box>
      <Typography variant="h5" gutterBottom>
        Alerts dashboard
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
        Showing alerts generated by the backend scoring pipeline. Use the toggle to focus on the last 7 days of
        activity.
      </Typography>

      <Box display="flex" alignItems="center" justifyContent="space-between" sx={{ mb: 2, gap: 2 }}>
        <Box display="flex" flexWrap="wrap" gap={1}>
          <Chip label={`Total: ${totalCount}`} size="small" />
          <Chip label={`Last 7 days: ${last7dCount}`} color="primary" size="small" />
          <Chip label={`Confirmed: ${confirmedCount}`} color="success" size="small" />
          <Chip label={`Watch list: ${watchListCount}`} color="warning" size="small" />
          <Chip label={`Pending: ${pendingCount}`} color="info" size="small" />
        </Box>
        <Button
          variant={showOnlyLast7Days ? 'contained' : 'outlined'}
          size="small"
          onClick={() => setShowOnlyLast7Days((v) => !v)}
        >
          {showOnlyLast7Days ? 'Show all alerts' : 'Show last 7 days only'}
        </Button>
      </Box>

      <Table size="small">
        <TableHead>
          <TableRow>
            <TableCell>ID</TableCell>
            <TableCell>Status</TableCell>
            <TableCell>Created</TableCell>
            <TableCell>Updated</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {alerts.map((a) => (
            <TableRow key={a.id} hover>
              <TableCell>
                <Link component={RouterLink} to={`/alerts/${a.id}`}>
                  {a.id}
                </Link>
              </TableCell>
              <TableCell>
                <Chip
                  label={a.status}
                  color={statusColor(a.status) as 'success' | 'warning' | 'default' | 'info'}
                  size="small"
                />
              </TableCell>
              <TableCell>{new Date(a.created_at).toLocaleString()}</TableCell>
              <TableCell>{new Date(a.updated_at).toLocaleString()}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Box>
  )
}


