import { useEffect, useState } from 'react'
import { Link as RouterLink } from 'react-router-dom'
import {
  Alert as MuiAlert,
  Box,
  Button,
  Chip,
  CircularProgress,
  Link,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  Typography,
  Card,
  CardContent,
  Grid,
} from '@mui/material'
import WarningIcon from '@mui/icons-material/Warning'
import CheckCircleIcon from '@mui/icons-material/CheckCircle'
import WatchLaterIcon from '@mui/icons-material/WatchLater'
import CancelIcon from '@mui/icons-material/Cancel'
import TrendingUpIcon from '@mui/icons-material/TrendingUp'
import api from '../api'

type AlertSummary = {
  id: number
  status: string
  created_at: string
  updated_at: string
  score_id: number
}

type AlertsResponse = {
  value: AlertSummary[]
  Count?: number
}

function statusColor(status: string) {
  switch (status) {
    case 'confirmed':
      return 'success'
    case 'watch_list':
      return 'warning'
    case 'dismissed':
      return 'default'
    default:
      return 'info'
  }
}

export default function AlertsListPage() {
  const [alerts, setAlerts] = useState<AlertSummary[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [showOnlyLast7Days, setShowOnlyLast7Days] = useState(true)

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        setLoading(true)
        const res = await api.get<AlertsResponse>('/alerts', { params: { limit: 200 } })
        if (!cancelled) {
          const maybeWrapped = res.data as Partial<AlertsResponse> | AlertSummary[]
          const value = Array.isArray(maybeWrapped)
            ? maybeWrapped
            : (maybeWrapped.value as AlertSummary[] | undefined) ?? []
          setAlerts(value)
        }
      } catch (e) {
        const message = e instanceof Error ? e.message : 'Failed to load alerts'
        if (!cancelled) {
          setError(message)
        }
      } finally {
        if (!cancelled) setLoading(false)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [])

  const now = new Date()
  const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)

  const filteredAlerts = showOnlyLast7Days
    ? alerts.filter((a) => new Date(a.created_at) >= sevenDaysAgo)
    : alerts

  const totalCount = alerts.length
  const last7dCount = alerts.filter((a) => new Date(a.created_at) >= sevenDaysAgo).length
  const confirmedCount = filteredAlerts.filter((a) => a.status === 'confirmed').length
  const watchListCount = filteredAlerts.filter((a) => a.status === 'watch_list').length
  const pendingCount = filteredAlerts.filter((a) => a.status === 'pending_review').length

  if (loading) {
    return (
      <Box display="flex" justifyContent="center" mt={4}>
        <CircularProgress />
      </Box>
    )
  }

  if (error) {
    return (
      <MuiAlert severity="error" sx={{ mt: 2 }}>
        {error}
      </MuiAlert>
    )
  }

  if (!alerts.length) {
    return (
      <Typography variant="body1" sx={{ mt: 2 }}>
        No alerts yet.
      </Typography>
    )
  }

  return (
    <Box>
      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" gutterBottom sx={{ fontWeight: 700, color: '#1a1a1a' }}>
          Alerts Dashboard
        </Typography>
        <Typography variant="body1" color="text.secondary" sx={{ mb: 3 }}>
          Monitor safety signals generated by the backend scoring pipeline. Review and manage alerts with real-time
          updates.
        </Typography>

        <Grid container spacing={2} sx={{ mb: 3 }}>
          <Grid item xs={12} sm={6} md={2.4}>
            <Card sx={{ background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', color: 'white' }}>
              <CardContent>
                <Box display="flex" alignItems="center" justifyContent="space-between">
                  <Box>
                    <Typography variant="caption" sx={{ opacity: 0.9 }}>
                      Total Alerts
                    </Typography>
                    <Typography variant="h4" sx={{ fontWeight: 700, mt: 0.5 }}>
                      {totalCount}
                    </Typography>
                  </Box>
                  <WarningIcon sx={{ fontSize: 40, opacity: 0.8 }} />
                </Box>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12} sm={6} md={2.4}>
            <Card sx={{ background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', color: 'white' }}>
              <CardContent>
                <Box display="flex" alignItems="center" justifyContent="space-between">
                  <Box>
                    <Typography variant="caption" sx={{ opacity: 0.9 }}>
                      Last 7 Days
                    </Typography>
                    <Typography variant="h4" sx={{ fontWeight: 700, mt: 0.5 }}>
                      {last7dCount}
                    </Typography>
                  </Box>
                  <TrendingUpIcon sx={{ fontSize: 40, opacity: 0.8 }} />
                </Box>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12} sm={6} md={2.4}>
            <Card sx={{ background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', color: 'white' }}>
              <CardContent>
                <Box display="flex" alignItems="center" justifyContent="space-between">
                  <Box>
                    <Typography variant="caption" sx={{ opacity: 0.9 }}>
                      Confirmed
                    </Typography>
                    <Typography variant="h4" sx={{ fontWeight: 700, mt: 0.5 }}>
                      {confirmedCount}
                    </Typography>
                  </Box>
                  <CheckCircleIcon sx={{ fontSize: 40, opacity: 0.8 }} />
                </Box>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12} sm={6} md={2.4}>
            <Card sx={{ background: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)', color: 'white' }}>
              <CardContent>
                <Box display="flex" alignItems="center" justifyContent="space-between">
                  <Box>
                    <Typography variant="caption" sx={{ opacity: 0.9 }}>
                      Watch List
                    </Typography>
                    <Typography variant="h4" sx={{ fontWeight: 700, mt: 0.5 }}>
                      {watchListCount}
                    </Typography>
                  </Box>
                  <WatchLaterIcon sx={{ fontSize: 40, opacity: 0.8 }} />
                </Box>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12} sm={6} md={2.4}>
            <Card sx={{ background: 'linear-gradient(135deg, #30cfd0 0%, #330867 100%)', color: 'white' }}>
              <CardContent>
                <Box display="flex" alignItems="center" justifyContent="space-between">
                  <Box>
                    <Typography variant="caption" sx={{ opacity: 0.9 }}>
                      Pending
                    </Typography>
                    <Typography variant="h4" sx={{ fontWeight: 700, mt: 0.5 }}>
                      {pendingCount}
                    </Typography>
                  </Box>
                  <CancelIcon sx={{ fontSize: 40, opacity: 0.8 }} />
                </Box>
              </CardContent>
            </Card>
          </Grid>
        </Grid>

        <Box display="flex" justifyContent="flex-end" sx={{ mb: 3 }}>
          <Button
            variant={showOnlyLast7Days ? 'contained' : 'outlined'}
            size="medium"
            onClick={() => setShowOnlyLast7Days((v) => !v)}
            sx={{ borderRadius: 2 }}
          >
            {showOnlyLast7Days ? 'Show all alerts' : 'Show last 7 days only'}
          </Button>
        </Box>
      </Box>

      <Paper elevation={0} sx={{ borderRadius: 3, overflow: 'hidden' }}>
        <Table>
          <TableHead>
            <TableRow sx={{ backgroundColor: '#f8f9fa' }}>
              <TableCell sx={{ fontWeight: 600 }}>ID</TableCell>
              <TableCell sx={{ fontWeight: 600 }}>Status</TableCell>
              <TableCell sx={{ fontWeight: 600 }}>Created</TableCell>
              <TableCell sx={{ fontWeight: 600 }}>Updated</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {filteredAlerts.map((a) => (
              <TableRow
                key={a.id}
                hover
                sx={{
                  '&:hover': { backgroundColor: '#f8f9fa' },
                  '&:last-child td': { border: 0 },
                }}
              >
                <TableCell>
                  <Link
                    component={RouterLink}
                    to={`/alerts/${a.id}`}
                    sx={{
                      color: 'primary.main',
                      fontWeight: 500,
                      textDecoration: 'none',
                      '&:hover': { textDecoration: 'underline' },
                    }}
                  >
                    #{a.id}
                  </Link>
                </TableCell>
                <TableCell>
                  <Chip
                    label={a.status.replace('_', ' ')}
                    color={statusColor(a.status) as 'success' | 'warning' | 'default' | 'info'}
                    size="small"
                    sx={{ fontWeight: 500 }}
                  />
                </TableCell>
                <TableCell>{new Date(a.created_at).toLocaleString()}</TableCell>
                <TableCell>{new Date(a.updated_at).toLocaleString()}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Paper>
    </Box>
  )
}


